dist: trusty
sudo: false
language: node_js
cache: yarn
node_js:
- '7'
- '6'
notifications:
  email: false
  pushover:
    api_key:
      secure: Rox3Am39BXAa0X6gqh/rpbIwXQ0g64RiPXlA124C6Db4ntUOs8vsfxiRvcI9nGMG/TIWmznHUXtCrQ+GkvKj2MCh4TaplSg2I36wS1uORSO9o0xG4w0vtKRocghqLXcNMnIqpq6vbU51C5an3ILOKO4+odlK0+GwEEqvgshXkoDBgVGEqlCV0tbtyO2nZJn+83lT+bWoLmsnC/PqkcCYM9SrCpf6Ia1HLIFtK8aDEy0771cAdBTcHM50iNeFQzu/E0UAZxg5Br1/UZmMoMyGYXPBETb9pqKA+juTJhbKxpuhVqCSey49QWCO9cuDfZkCpJ9aQx8BQFjtUHM3/1sk6RjEVpliDv3Z42bsce3GR15xMN2dAxlfQenafMXM3aNilpxttKYyhMudSMu/SC7PRAED/sWiEBO+oYNYpBeY9g0dF/0vjxXvGOamY7m4GH+CV5o7PvltLMU38xsIlFTE36XFpJnkeBPzPp92OnZgV2hpOo0Hl1EqMo0wwfD29rzTogZiqxwYXiJ4e0oRM5GJ2FDCPjx6Qz1D6lx0YKNdfJUiBv/WGj8EBOESdTy9nnLOvhuiTDm7VkNpt7gvcg5hmnskh5yxEm71k4hnqVAlZgb8gsSWPuMAzUj9kGrgT7OatlkSO71uu4StgyreljTjEjNDrYBbAHu5uaY9w/MwwjE=
    users:
      secure: Nyt4nVBebZox1GOeuGQkIoJ6pCpBD7dCw+uO87RReOkcOzz46DEKMK+isc7GZrXDeWMTV40l/h3PNNWl359Wf4fiO+e+UY6DaVg3CM97ak4l26VGP+hTuq1B4myKrMnvt88vKFetbx2HmiLWyDl6fB/DbYnRXurlX7IEAA6qz02LTEqUkes7qbWwFRjpJOO3CkMBMb6mFiiXf9UAoIIcX/Zgj9cBt6SdXHgka+caevrXsfAYdyScxL5FnXYur7yi7FTMwdRVOtE7IM4TTSumU5jy0hVszKpobG314hzjRUl5jgj3Sy7/Ag+fR/xqiRH08EoLnKWPLw+j84RiZD5DCBWgA2A9OnA4M+P56nv4OzAqBzYWNFU3Pd+QOpcI5+U4mMdfojME+R8ZRWJCp8W3w0rCTA4lpzcKgp3khalFum3wnroTHmwNBzL5KpMfCxItgb/4QsSseaDsWqKHvf5CY65CliCjRRJvzQbiHDWDSSEtt1POMmb4qUnuvjfJtzTUFOVYyCxnNahyeQpfUOXz2j9Jht4mBQb5p09arqSdaCull5WtVBnKXNjzOl+gP2lV2VigDzDT8+EEm/v/l/knOdz/8x0/oBpffCQLs9AM6YcsC/DuUYIb3nFjLr0AHcUF10x08iljKbBVvmlWogoCDfIxq/RPOIXXGTQh0gzSnEA=
